# Docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
  - stage: Build
    displayName: Build image
    jobs:
    - job: Build
      displayName: Build
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: Docker@2
        displayName: Build an image
        inputs:
          containerRegistry: 'DOCKER-HUB'
          repository: 'jgutig/aforo255'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: '$(tag)'
      
      - task: CopyFiles@2
        inputs:
          Contents: '**/*.yaml'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
      
      ################################################ DEPLOY ###################################################
  - stage: Deploy
    displayName: Build
    jobs:
      - job: Deploy
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        
        steps:
        - task: DownloadBuildArtifacts@0
          inputs:
            buildType: 'current'
            downloadType: 'single'
            downloadPath: '$(System.ArtifactsDirectory)'
